
name: Build and Push Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t docker.pkg.github.com/namespace-team/ruby2.6.5-alpine-mysql2/ruby2.6.5-alpine-mysql2 .

    - name: Login to Github Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u rawatnaresh --password-stdin
    - name: Pushing Doker Image to DokcerHub
      run: docker push docker.pkg.github.com/namespace-team/ruby2.6.5-alpine-mysql2/ruby2.6.5-alpine-mysql2